### ISSUE TITLE
configure.R uses incorrect values for target arch which breaks build on some platforms

### ISSUE THREAD

**Issue by barracuda156** [tylermorganwall/libdeflate#1]
The configure script uses inappropriate method to detect target arch: https://github.com/tylermorganwall/libdeflate/blob/b5d86ec6d40b884836f15e31f41c04ed0c53a590/tools/config/configure.R#L42
Apparently it uses `uname -m`, which returns cpu family of a build machine, and for powerpc it returns `Power Macintosh`.

That is fed into CMake, and in result compiler checks fail.

```
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/opt/local/share/cmake-3.31/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:22 (project)"
    message: |
      The system is: Darwin - 10.8.0 - powerpc
  -
    kind: "message-v1"
    backtrace:
      - "/opt/local/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/opt/local/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/opt/local/share/cmake-3.31/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:22 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: /opt/local/bin/gcc-mp-14 
      Build flags: -fPIC;-fvisibility=hidden
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "a.out"
      
      The C compiler identification is GNU, found in:
        /opt/local/var/macports/build/_opt_local_ppcports_R_R-libdeflate/R-libdeflate/work/libdeflate/src/libdeflate/build/CMakeFiles/3.31.7/CompilerIdC/a.out
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "/opt/local/share/cmake-3.31/Modules/CMakeDetermineCompilerABI.cmake:74 (try_compile)"
      - "/opt/local/share/cmake-3.31/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:22 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "/opt/local/var/macports/build/_opt_local_ppcports_R_R-libdeflate/R-libdeflate/work/libdeflate/src/libdeflate/build/CMakeFiles/CMakeScratch/TryCompile-zCfGSd"
      binary: "/opt/local/var/macports/build/_opt_local_ppcports_R_R-libdeflate/R-libdeflate/work/libdeflate/src/libdeflate/build/CMakeFiles/CMakeScratch/TryCompile-zCfGSd"
    cmakeVariables:
      CMAKE_C_FLAGS: "-fPIC -fvisibility=hidden"
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: "-Wl,-headerpad_max_install_names -L/opt/local/lib -lMacportsLegacySupport -Wl,-rpath,/opt/local/lib/libgcc -arch ppc"
      CMAKE_OSX_ARCHITECTURES: "Power Macintosh"
      CMAKE_OSX_DEPLOYMENT_TARGET: "10.6"
      CMAKE_OSX_SYSROOT: "/Developer/SDKs/MacOSX10.6.sdk"
      CMAKE_POSITION_INDEPENDENT_CODE: "ON"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: '/opt/local/var/macports/build/_opt_local_ppcports_R_R-libdeflate/R-libdeflate/work/libdeflate/src/libdeflate/build/CMakeFiles/CMakeScratch/TryCompile-zCfGSd'
        
        Run Build Command(s): /opt/local/bin/cmake -E env VERBOSE=1 /usr/bin/make -f Makefile cmTC_a3090/fast
        make  -f CMakeFiles/cmTC_a3090.dir/build.make CMakeFiles/cmTC_a3090.dir/build
        make[1]: Entering directory `/opt/local/var/macports/build/_opt_local_ppcports_R_R-libdeflate/R-libdeflate/work/libdeflate/src/libdeflate/build/CMakeFiles/CMakeScratch/TryCompile-zCfGSd'
        Building C object CMakeFiles/cmTC_a3090.dir/CMakeCCompilerABI.c.o
        /opt/local/bin/gcc-mp-14   -fPIC -fvisibility=hidden  -arch Power Macintosh -isysroot /Developer/SDKs/MacOSX10.6.sdk -mmacosx-version-min=10.6 -fPIE   -v -Wl,-v -o CMakeFiles/cmTC_a3090.dir/CMakeCCompilerABI.c.o -c /opt/local/share/cmake-3.31/Modules/CMakeCCompilerABI.c
        gcc-mp-14: error: this compiler does not support 'Power'
        Using built-in specs.
        COLLECT_GCC=/opt/local/bin/gcc-mp-14
        Target: powerpc-apple-darwin10
        Configured with: /opt/local/var/macports/build/_opt_local_ppcports_lang_gcc14/gcc14/work/gcc-14.2.0/configure --prefix=/opt/local --build=powerpc-apple-darwin10 --enable-languages=c,c++,objc,obj-c++,lto,fortran,jit --libdir=/opt/local/lib/gcc14 --infodir=/opt/local/share/info --mandir=/opt/local/share/man --datarootdir=/opt/local/share/gcc-14 --with-local-prefix=/opt/local --with-system-zlib --disable-nls --program-suffix=-mp-14 --with-gxx-include-dir=/opt/local/include/gcc14/c++/ --with-gmp=/opt/local --with-mpfr=/opt/local --with-mpc=/opt/local --with-isl=/opt/local --with-zstd=/opt/local --enable-checking=release --disable-multilib --enable-lto --enable-libstdcxx-time --without-build-config --with-as=/opt/local/bin/as --with-ld=/opt/local/bin/ld --with-ar=/opt/local/bin/ar --with-bugurl=https://trac.macports.org/newticket --enable-host-shared --with-darwin-extra-rpath=/opt/local/lib/libgcc --with-libiconv-prefix=/opt/local --disable-tls --with-tune-cpu=G5 --with-gxx-libcxx-include-dir=/opt/local/libexec/gcc14/libc++/include/c++/v1 --with-pkgversion='MacPorts gcc14 14.2.0_2+G5+stdlib_flag'
        Thread model: posix
        Supported LTO compression algorithms: zlib zstd
        gcc version 14.2.0 (MacPorts gcc14 14.2.0_2+G5+stdlib_flag) 
        make[1]: *** [CMakeFiles/cmTC_a3090.dir/CMakeCCompilerABI.c.o] Error 1
        make[1]: Leaving directory `/opt/local/var/macports/build/_opt_local_ppcports_R_R-libdeflate/R-libdeflate/work/libdeflate/src/libdeflate/build/CMakeFiles/CMakeScratch/TryCompile-zCfGSd'
        make: *** [cmTC_a3090/fast] Error 2
        
      exitCode: 2
  -
    kind: "try_compile-v1"
    backtrace:
      - "/opt/local/share/cmake-3.31/Modules/CMakeTestCCompiler.cmake:56 (try_compile)"
      - "CMakeLists.txt:22 (project)"
    checks:
      - "Check for working C compiler: /opt/local/bin/gcc-mp-14"
    directories:
      source: "/opt/local/var/macports/build/_opt_local_ppcports_R_R-libdeflate/R-libdeflate/work/libdeflate/src/libdeflate/build/CMakeFiles/CMakeScratch/TryCompile-rlE8SN"
      binary: "/opt/local/var/macports/build/_opt_local_ppcports_R_R-libdeflate/R-libdeflate/work/libdeflate/src/libdeflate/build/CMakeFiles/CMakeScratch/TryCompile-rlE8SN"
    cmakeVariables:
      CMAKE_C_FLAGS: "-fPIC -fvisibility=hidden"
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: "-Wl,-headerpad_max_install_names -L/opt/local/lib -lMacportsLegacySupport -Wl,-rpath,/opt/local/lib/libgcc -arch ppc"
      CMAKE_OSX_ARCHITECTURES: "Power Macintosh"
      CMAKE_OSX_DEPLOYMENT_TARGET: "10.6"
      CMAKE_OSX_SYSROOT: "/Developer/SDKs/MacOSX10.6.sdk"
      CMAKE_POSITION_INDEPENDENT_CODE: "ON"
    buildResult:
      variable: "CMAKE_C_COMPILER_WORKS"
      cached: true
      stdout: |
        Change Dir: '/opt/local/var/macports/build/_opt_local_ppcports_R_R-libdeflate/R-libdeflate/work/libdeflate/src/libdeflate/build/CMakeFiles/CMakeScratch/TryCompile-rlE8SN'
        
        Run Build Command(s): /opt/local/bin/cmake -E env VERBOSE=1 /usr/bin/make -f Makefile cmTC_1eff8/fast
        make  -f CMakeFiles/cmTC_1eff8.dir/build.make CMakeFiles/cmTC_1eff8.dir/build
        make[1]: Entering directory `/opt/local/var/macports/build/_opt_local_ppcports_R_R-libdeflate/R-libdeflate/work/libdeflate/src/libdeflate/build/CMakeFiles/CMakeScratch/TryCompile-rlE8SN'
        Building C object CMakeFiles/cmTC_1eff8.dir/testCCompiler.c.o
        /opt/local/bin/gcc-mp-14   -fPIC -fvisibility=hidden  -arch Power Macintosh -isysroot /Developer/SDKs/MacOSX10.6.sdk -mmacosx-version-min=10.6 -fPIE -o CMakeFiles/cmTC_1eff8.dir/testCCompiler.c.o -c /opt/local/var/macports/build/_opt_local_ppcports_R_R-libdeflate/R-libdeflate/work/libdeflate/src/libdeflate/build/CMakeFiles/CMakeScratch/TryCompile-rlE8SN/testCCompiler.c
        gcc-mp-14: error: this compiler does not support 'Power'
        make[1]: *** [CMakeFiles/cmTC_1eff8.dir/testCCompiler.c.o] Error 1
        make[1]: Leaving directory `/opt/local/var/macports/build/_opt_local_ppcports_R_R-libdeflate/R-libdeflate/work/libdeflate/src/libdeflate/build/CMakeFiles/CMakeScratch/TryCompile-rlE8SN'
        make: *** [cmTC_1eff8/fast] Error 2
        
      exitCode: 2
...
```

I do not really understand what is the need to detect the arch at all – it is not arch of the target, but cpu family of the build machine – and by default a compiler will use that value anyway. But if such need is there, then some alternative mechanism is to be used.

P. S. I have initially thought it is a CMake fault, but no, it originates from R script here. See: https://gitlab.kitware.com/cmake/cmake/-/issues/26949
